# Generated by Django 4.2.6 on 2023-11-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0003_alter_signup_options_remove_signup_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='confirm_password',
            field=models.TextField(default=''),
        ),
    ]
