# Generated by Django 4.2.6 on 2023-11-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0004_signup_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='confirm_password',
            field=models.TextField(blank=True),
        ),
    ]
