# Generated by Django 4.2.6 on 2023-11-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0005_alter_signup_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='signup',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signup',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
