# Generated by Django 4.2.6 on 2023-11-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0006_remove_signup_confirm_password_signup_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(default='Phoenix', max_length=255)),
                ('your_phone', models.IntegerField(default='0123456789')),
                ('your_email', models.EmailField(default='Phoenix@gmail.com', max_length=255)),
                ('your_address', models.CharField(default='Phoenix', max_length=255)),
                ('your_schedule', models.CharField(default='Phoenix', max_length=255)),
                ('your_date', models.CharField(default='Phoenix', max_length=255)),
                ('your_message', models.TextField(default='Phoenix', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Specialty', models.CharField(max_length=40)),
                ('Reg_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Sex', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
                ('ContactNo', models.IntegerField(null=True)),
            ],
        ),
    ]
