# Generated by Django 4.2.6 on 2023-11-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0007_appoinment_doctor_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appoinment',
        ),
    ]
