# Generated by Django 4.2.6 on 2023-11-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0008_delete_appoinment'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(default='Nuva', max_length=255)),
                ('your_phone', models.IntegerField(default='0123456789')),
                ('your_email', models.EmailField(default='nuvanthaabey@gmail.com', max_length=255)),
                ('your_address', models.CharField(default='Nuva', max_length=255)),
                ('your_schedule', models.CharField(default='Nuva', max_length=255)),
                ('your_date', models.CharField(default='Nuva', max_length=255)),
                ('your_message', models.TextField(default='Nuva', max_length=255)),
            ],
        ),
    ]
